### PR TITLE
Add mobile support

### PR DESCRIPTION
**Pull request by dktharrop**
Makes extension work on mobile by checking userAgent and getting a different class name.

### CODE REVIEW

**Comment by dktharrop** [comment]
just realized i left in a really silly bug, let me fix that real quick

**Comment by dktharrop** [comment]
Apparently mobile breaks because at seemingly random points the mobile site uses a different class name for the result URLs. The class name always contains "result-url-containter" so I just changed it to match any class which name contains that string.

**Comment by mriooo** [comment]
Cheers! I'll take a look at it this evening :)

**Comment by mriooo** [comment]
thanks, I've merged the PR and it will be in the next version. I wonder, how do you use the addon with the firefox mobile app? since they restricted the use of addons on the android version of ff

**Comment by dktharrop** [comment]
[If you use firefox nightly for android you can load addons using collections](https://blog.mozilla.org/addons/2020/09/29/expanded-extension-support-in-firefox-for-android-nightly/)

**Pull request merged**
